#!/bin/fish

set items (busctl --user \
  get-property org.kde.StatusNotifierWatcher \
  /StatusNotifierWatcher \
  org.kde.StatusNotifierWatcher \
  RegisteredStatusNotifierItems | sed 's/as [0-9]\+ //g' | tr -d '"' | tr ' ' '\n' | choose -f / 0)

set qqs (busctl --user list | rg qq | choose 0)

set dest (comm -12 (echo "$qqs" | sort | push) (echo "$items" | sort | push))

if test -z "$dest"
  /bin/linuxqq
  return
end

busctl --user call "$dest" /StatusNotifierItem org.kde.StatusNotifierItem Activate ii 0 0
