#!/bin/fish

set dest (busctl --user list | rg 'org.kde.StatusNotifierItem-[0-9]+-1' | choose 0)
test -n "$dest"
and busctl --user call "$dest" /StatusNotifierItem org.kde.StatusNotifierItem Activate ii 0 0
or /bin/wechat
