#!/bin/bash

dest=$(busctl --user list | rg 'org.kde.StatusNotifierItem-[0-9]+-1' | awk '{print $1}')
(
  busctl --user call "$dest" /StatusNotifierItem org.kde.StatusNotifierItem Activate ii 0 0 && (
    sleep 0.1
    hyprctl dispatch movetoworkspace +0, 'class:^(wechat)$' | rg ok -q
  )
) || /bin/wechat
