preload = ~/Pictures/wallpaper/blue-archive-siroko.png
preload = ~/Pictures/wallpaper/小羊.jpg
wallpaper = eDP-1, ~/Pictures/wallpaper/小羊.jpg
wallpaper = HDMI-A-1, ~/Pictures/wallpaper/blue-archive-siroko.png

